name: "Feature Request"
description: "機能追加・改善案用テンプレート"
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 機能要望
        追加したい機能や改善したい点について記載してください。

  - type: textarea
    id: description
    attributes:
      label: 概要
      placeholder: |
        どのような機能なのか、なぜ必要なのか、誰に影響するのかを書いてください。
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 備考
      placeholder: 補足情報があれば
    validations:
      required: false
  
  - type: textarea
    id: task
    attributes:
      label: タスク
      description: 実装・追加するタスクを記載してください．
      value: |
        - [ ]
        - [ ]
        - [ ]
        ...
    validations:
      required: true